create table if not exists "user_saved_packages" (
  "id" uuid primary key default gen_random_uuid(),
  "user_id" uuid not null,
  "package_id" uuid not null references "packages" ("id") on delete cascade,
  "created_at" timestamptz not null default now(),
  unique ("user_id", "package_id")
);

create index if not exists "user_saved_packages_user_id_idx" on "user_saved_packages" ("user_id");
create index if not exists "user_saved_packages_package_id_idx" on "user_saved_packages" ("package_id");
create index if not exists "user_saved_packages_created_at_idx" on "user_saved_packages" ("created_at");

insert into "destination_categories" ("title", "slug", "description", "image_url", "sort_order") values
  ('Mountains & Treks', 'mountains-treks', 'High-altitude escapes, ridgelines, and walking journeys.', '', 100),
  ('Beaches', 'beaches', 'Coastlines, surf towns, and barefoot slow living.', '', 90),
  ('Temples & Spiritual', 'temples-spiritual', 'Sacred cities, rituals, and reflective journeys.', '', 80),
  ('Heritage & Culture', 'heritage-culture', 'Historic cities, forts, and living traditions.', '', 70),
  ('Nature & Forest', 'nature-forest', 'Tea gardens, waterfalls, and green escapes.', '', 60),
  ('Adventure', 'adventure', 'High-energy trips and offbeat exploration.', '', 50),
  ('Hill Stations', 'hill-stations', 'Cool-climate getaways with scenic viewpoints.', '', 40),
  ('Wildlife', 'wildlife', 'National parks, safaris, and forest immersion.', '', 30)
on conflict ("slug") do nothing;

insert into "destinations" ("category_id", "name", "title", "slug", "state", "city", "short_description", "long_description", "tags", "hero_image_url", "best_season", "estimated_budget", "ideal_duration_days", "travel_tips", "featured", "is_active")
select c.id, v.title, v.title, v.slug, v.state, v.city, v.short_description, v.long_description, v.tags, v.hero_image_url, v.best_season, v.estimated_budget, v.ideal_duration_days, v.travel_tips, v.featured, true
from (values
  ('mountains-treks', 'Manali', 'manali', 'Himachal Pradesh', 'Manali', 'Snowy peaks, cafes, and easy access to adventure.', 'A classic mountain base for travelers who want a little of everything: snowy views, cafes, river walks, and access to Solang Valley and nearby treks.', 'snow, cafes, valleys', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1600&q=80', 'Oct to Mar', '₹18k - ₹38k', 4, 'Book stays near Old Manali for a calmer experience.', true),
  ('mountains-treks', 'Leh Ladakh', 'leh-ladakh', 'Ladakh', 'Leh', 'Desert mountains, monasteries, and cinematic roads.', 'A high-altitude journey with unforgettable passes, dramatic light, monasteries, and clear skies that make every stop feel bigger than life.', 'high altitude, road trip, monasteries', 'https://images.unsplash.com/photo-1506012787146-f9c5c7d0f8f4?auto=format&fit=crop&w=1600&q=80', 'May to Sep', '₹28k - ₹75k', 6, 'Acclimatize on arrival and hydrate constantly.', true),
  ('beaches', 'Goa', 'goa', 'Goa', 'North Goa', 'Laid-back beaches, nightlife, and easy sunshine.', 'A flexible beach destination that works for slow mornings, island hopping, seafood dinners, and lively evenings without forcing a single pace.', 'beaches, nightlife, seafood', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80', 'Nov to Feb', '₹16k - ₹42k', 4, 'Stay close to the beach you want to revisit at sunset.', true),
  ('beaches', 'Andaman', 'andaman', 'Andaman & Nicobar', 'Port Blair', 'Clear water, quiet islands, and coral blue lagoons.', 'Island time feels slower here. Think glass-clear water, ferry hops, snorkeling, and beaches that still feel spacious even in season.', 'islands, snorkeling, beaches', 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=80', 'Oct to May', '₹32k - ₹68k', 5, 'Plan ferries early; island transfers sell out quickly.', true),
  ('temples-spiritual', 'Varanasi', 'varanasi', 'Uttar Pradesh', 'Varanasi', 'Riverside rituals, ancient lanes, and timeless energy.', 'A deep cultural and spiritual city where ghats, dawn aartis, and layered lanes create a powerful place to slow down and observe.', 'ghats, rituals, culture', 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1600&q=80', 'Oct to Mar', '₹14k - ₹30k', 3, 'Book a sunrise boat ride at least a day ahead.', true),
  ('temples-spiritual', 'Rishikesh', 'rishikesh', 'Uttarakhand', 'Rishikesh', 'Riverfront calm with yoga, cafes, and mountain air.', 'A balance of spiritual quiet and gentle adventure, ideal for travelers who want river views, wellness spaces, and an easy reset.', 'yoga, river, wellness', 'https://images.unsplash.com/photo-1549992722-65f9e1a0875e?auto=format&fit=crop&w=1600&q=80', 'Sep to Apr', '₹12k - ₹28k', 4, 'Choose a stay near the river but away from the busiest bridge crowds.', true),
  ('heritage-culture', 'Udaipur', 'udaipur', 'Rajasthan', 'Udaipur', 'Lakes, palaces, and slow cultural wandering.', 'A polished heritage escape with lake views, palace architecture, rooftop meals, and a pace that rewards lingering over detail.', 'lakes, palaces, heritage', 'https://images.unsplash.com/photo-1562426509-5044f3f84a27?auto=format&fit=crop&w=1600&q=80', 'Oct to Mar', '₹20k - ₹50k', 4, 'Sunset boat rides are one of the easiest ways to anchor the trip.', true),
  ('heritage-culture', 'Hampi', 'hampi', 'Karnataka', 'Hampi', 'Ruins, boulders, and a distinct ancient mood.', 'An open-air heritage landscape where ruins, riverbanks, and boulder fields make sightseeing feel like wandering through an epic set.', 'ruins, temples, boulders', 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1600&q=80', 'Oct to Feb', '₹15k - ₹32k', 3, 'Use bicycles or scooters to cover the wider heritage zone.', true),
  ('nature-forest', 'Coorg', 'coorg', 'Karnataka', 'Madikeri', 'Coffee estates, mist, and gentle green slopes.', 'An easy nature reset with plantation stays, misty roads, and enough variety for both quiet travelers and short activity bursts.', 'coffee, plantations, mist', 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1600&q=80', 'Oct to Mar', '₹18k - ₹36k', 4, 'Stay in an estate homestay if you want the full green retreat feel.', true),
  ('nature-forest', 'Meghalaya', 'meghalaya', 'Meghalaya', 'Shillong', 'Rain, roots, waterfalls, and living landscapes.', 'A lush east-bound escape that feels alive in every season, especially for travelers who want monsoon texture and forest scenery.', 'waterfalls, rain, forest', 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1600&q=80', 'Apr to Oct', '₹24k - ₹48k', 5, 'Carry a light rain layer even when the forecast looks clear.', true),
  ('adventure', 'Kasol', 'kasol', 'Himachal Pradesh', 'Kasol', 'Trailheads, cafes, and an easygoing mountain base.', 'A compact adventure hub where short treks, river walks, and a relaxed traveler community make it easy to extend your stay.', 'treks, rivers, cafes', 'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b6c?auto=format&fit=crop&w=1600&q=80', 'Apr to Jun', '₹14k - ₹28k', 4, 'Use Kasol as a base if you want multiple trail options.', true),
  ('adventure', 'Rishikesh', 'rishikesh-adventure', 'Uttarakhand', 'Rishikesh', 'Rafting, cliff views, and active reset days.', 'A more active take on Rishikesh with rafting, ropes, and easy access to a high-energy outdoor plan.', 'rafting, adventure, river', 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1600&q=80', 'Sep to May', '₹11k - ₹24k', 3, 'Book rafting slots early in peak weekends.', true),
  ('hill-stations', 'Ooty', 'ooty', 'Tamil Nadu', 'Ooty', 'Toy train vibes, tea gardens, and cool air.', 'A classic hill-station trip with botanical gardens, lake stops, and a pace that feels built for relaxed morning walks.', 'tea, lakes, cool climate', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80', 'Mar to Jun', '₹16k - ₹34k', 4, 'A few early starts help you avoid the busiest viewpoints.', true),
  ('hill-stations', 'Munnar', 'munnar', 'Kerala', 'Munnar', 'Tea estates, rolling greens, and slow scenic drives.', 'A green hill escape that is especially strong for travelers who want scenic drives, plantation views, and a softer travel rhythm.', 'tea estates, hills, mist', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80', 'Sep to May', '₹20k - ₹42k', 4, 'Plan at least one full day for estate roads and viewpoints.', true),
  ('wildlife', 'Jim Corbett', 'jim-corbett', 'Uttarakhand', 'Ramnagar', 'Safaris, river edges, and forest quiet.', 'One of the easiest wildlife-first escapes for travelers who want a proper safari feel without committing to a very long trip.', 'safari, forest, wildlife', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1600&q=80', 'Nov to Jun', '₹18k - ₹40k', 3, 'Reserve safari windows early, especially for weekends.', true),
  ('wildlife', 'Kaziranga', 'kaziranga', 'Assam', 'Kaziranga', 'Grasslands, rhinos, and wide open wild terrain.', 'A strong wildlife destination with distinct grassland scenery and a different visual tone from the usual hill or beach trip.', 'rhinos, safari, grasslands', 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1600&q=80', 'Nov to Apr', '₹24k - ₹52k', 3, 'Choose a stay with quick access to the park entry gate.', true)
) as v(category_slug, title, slug, state, city, short_description, long_description, tags, hero_image_url, best_season, estimated_budget, ideal_duration_days, travel_tips, featured)
join "destination_categories" c on c.slug = v.category_slug
on conflict ("slug") do nothing;
insert into "packages" ("destination_id", "title", "slug", "description", "duration_days", "price_amount", "price_currency", "features", "hero_image_url", "is_active")
select d.id, p.title, p.slug, p.description, p.duration_days, p.price_amount, p.price_currency, p.features, p.hero_image_url, true
from (values
  ('manali', 'Manali Winter Reset', 'manali-winter-reset', 'A scenic mountain stay with easy treks, cafes, and one strong snowy highlight.', 4, 18999, 'INR', 'Stay in Old Manali, Solang Valley access, breakfast, local transfers', 'https://images.unsplash.com/photo-1549921296-3c3f7c1f8f21?auto=format&fit=crop&w=1600&q=80'),
  ('leh-ladakh', 'Leh Ladakh Signature Loop', 'leh-ladakh-signature-loop', 'A high-altitude road journey built around acclimatization, scenery, and calm pacing.', 7, 45999, 'INR', 'Airport pickup, curated route plan, stays, support window', 'https://images.unsplash.com/photo-1506012787146-f9c5c7d0f8f4?auto=format&fit=crop&w=1600&q=80'),
  ('goa', 'Goa Slow Coast Escape', 'goa-slow-coast-escape', 'Beach mornings, seafood dinners, and enough breathing room to actually unwind.', 4, 21999, 'INR', 'Beach stay, breakfast, sunset planning, local support', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80'),
  ('andaman', 'Andaman Island Drift', 'andaman-island-drift', 'Island hopping, snorkeling-ready time, and a clear-water itinerary.', 5, 38999, 'INR', 'Ferry guidance, island stay, breakfast, snorkel stop planning', 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=80'),
  ('varanasi', 'Varanasi Dawn & Ghats', 'varanasi-dawn-ghats', 'A short spiritual break centered on sunrise, riverside rituals, and the old city.', 3, 14999, 'INR', 'Boat sunrise, ghat walk plan, heritage stay, local guide notes', 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1600&q=80'),
  ('rishikesh', 'Rishikesh Calm Flow', 'rishikesh-calm-flow', 'A balanced retreat for yoga, river views, and slower mornings.', 4, 17999, 'INR', 'Riverside stay, yoga-friendly pacing, breakfast, support', 'https://images.unsplash.com/photo-1549992722-65f9e1a0875e?auto=format&fit=crop&w=1600&q=80'),
  ('udaipur', 'Udaipur Lake Heritage', 'udaipur-lake-heritage', 'A polished heritage stay with lake moments and rooftop evenings.', 4, 26999, 'INR', 'Lakeview stay, heritage walk, boat timing tips, breakfast', 'https://images.unsplash.com/photo-1562426509-5044f3f84a27?auto=format&fit=crop&w=1600&q=80'),
  ('hampi', 'Hampi Ruins & Boulders', 'hampi-ruins-boulders', 'An immersive heritage loop through ruins, cycling routes, and calm river zones.', 3, 16999, 'INR', 'Cycling support, heritage route, stay, local tips', 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1600&q=80'),
  ('coorg', 'Coorg Coffee Trails', 'coorg-coffee-trails', 'A plantation-led break with easy drives and strong green scenery.', 4, 20999, 'INR', 'Estate stay, breakfast, plantation walk, local transfer help', 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1600&q=80'),
  ('meghalaya', 'Meghalaya Waterfall Weekender', 'meghalaya-waterfall-weekender', 'A lush, rain-ready itinerary built around views, villages, and moving landscapes.', 5, 27999, 'INR', 'Scenic route plan, breakfast, local support, transfer guidance', 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1600&q=80'),
  ('kasol', 'Kasol Trail Starter', 'kasol-trail-starter', 'A relaxed adventure package with short treks and mountain downtime.', 4, 15999, 'INR', 'Trail guidance, café district stay, breakfast, local support', 'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b6c?auto=format&fit=crop&w=1600&q=80'),
  ('rishikesh-adventure', 'Rishikesh White Water Kickoff', 'rishikesh-white-water-kickoff', 'A faster-paced version of Rishikesh for rafting and outdoor activity.', 3, 13999, 'INR', 'Rafting planning, stay, breakfast, activity timing support', 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1600&q=80'),
  ('ooty', 'Ooty Hill Station Classic', 'ooty-hill-station-classic', 'Tea gardens, cool air, and an easy hill-station reset.', 4, 19999, 'INR', 'Tea estate stay, breakfast, scenic route, travel support', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80'),
  ('munnar', 'Munnar Green Escape', 'munnar-green-escape', 'A slow mountain stay around tea estates and scenic drives.', 4, 22499, 'INR', 'Tea estate stay, breakfast, local transfers, route notes', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80'),
  ('jim-corbett', 'Jim Corbett Safari Break', 'jim-corbett-safari-break', 'Forest quiet, safari timing, and a weekend that feels distinct from city travel.', 3, 22999, 'INR', 'Safari help, stay, breakfast, transfer support', 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1600&q=80'),
  ('kaziranga', 'Kaziranga Rhino Run', 'kaziranga-rhino-run', 'A wildlife-focused stay in one of India’s most iconic grassland parks.', 3, 31999, 'INR', 'Park timing guidance, stay, breakfast, support', 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1600&q=80')
) as p(destination_slug, title, slug, description, duration_days, price_amount, price_currency, features, hero_image_url)
join "destinations" d on d.slug = p.destination_slug
on conflict ("slug") do nothing;
